### ISSUE TITLE
404 for some valid reference doc links

### ISSUE THREAD

**Issue by iamveritas** [eosnetworkfoundation/devdocs#13]
go here
http://docs.eosnetwork.com/next/eosdocs/smart-contracts/mandel-cdt/how-to-guides/multi-index/how-to-modify-data-in-a-multi-index-table/

and click the `multi-index::modify` link
it shows 404
the link is valid (http://docs.eosnetwork.com/next/reference/mandel-cdt/group__multiindex.html#ga4b3556ef69c7faa917f185ae33a34442)
you can open it in a separate tab and it will load fine.

**Comment by ericpassmore** [comment]
Wont fix, need full path including fully qualified host ex: http://docs.eosnetwork.com 
Will be fixed once issue #4 is resolved
